### ISSUE TITLE
Hatalı Statement ve Cookie Parsing

### ISSUE THREAD

**Issue by fikret0** [RecepDuranBagiryanik/Cookie-Okuma-Sistemi#1]
Merhaba.
Bu Issue'yi kodunuzdaki hatayı bildirmek için açtım.
```php
$cookie = $_SERVER["HTTP_COOKIE"]; //TR::Cookieleri Çekme Bölümü

if ($cookie==strpos("$cookie", "rememberMe")) { //Cookie Kontrol Bölümü
	echo "Cookie Okundu!"; //Cookie Varsa
} else {
	echo "Cookie Okunamadı!"; //Cookie Yoksa
}
```

```php
$cookie==strpos("$cookie", "rememberMe")
```
bölümünde tamamıyla bir yanlışlık var. 
1. Özellikle cookieleri ``$_SERVER["HTTP_COOKIE"];`` yöntemiyle almamanız gerekirdi.
    Bu yöntem, **;** ile ayrılmış cookieleri ifade eder. Yani "rememberMe" başka bir cookienin değeri de olabilirdi.

2. **$cookie** bir boolean değil.

```php
if(isset($_COOKIE["rememberMe"])){
      echo "Cookie Okundu!";
}
else{
      echo "Cookie Okunamadı!";
}
```
yöntemini kullanmanızı tavsiye ederim. İyi günler.

**Comment by RecepBagiryanik** [comment]
dostum bir anlık dalgınlığıma gelmiş kusura bakma düzeltiyorum
